### ISSUE TITLE
Is this a writing error: attention.permute(0,1,2)?

### ISSUE THREAD

**Issue by zhuangzhichen** [heykeetae/Self-Attention-GAN#11]
hello, 
in sagan_models.py: 
out = torch.bmm(proj_value,attention.permute(0,1,2))  
do you want to transpose attention? but .permute(0,1,2) makes no change
from Han's paper eq(2), I think  it is .permute(0,2,1), 
or did I understand anything wrong?

**Comment by cheonbok94** [comment]
Thank you! @zhuangzhichen  
I forgot to update the latest fixed version. 
You're right. permute(0,2,1) is correct permutation.( Batch * Q_uery* Key -> Batch*Key*Query)
