### ISSUE TITLE
two-timescale update rule (TTUR)

### ISSUE THREAD

**Issue by taki0112** [heykeetae/Self-Attention-GAN#4]
Could you tell me where in the code is ***TTUR*** ? 

Thank you

**Comment by heykeetae** [comment]
To my knowledge, TTUR refers to setting different learning rate for the generator and the discriminator, g_lr=0.0001 and d_lr=0.0004 in the code respectively, as guided by the paper.

**Comment by zhangqianhui** [comment]
very simple
