### ISSUE TITLE
is there no activation on self attn layer?

### ISSUE THREAD

**Issue by caffeinism** [heykeetae/Self-Attention-GAN#40]
https://github.com/heykeetae/Self-Attention-GAN/blob/8714a54ba5027d680190791ba3a6bb08f9c9a129/sagan_models.py#L13

self attn layer's constructor has activation parameter but don't use that parameter.

**Comment by 787629504** [comment]
Same question. Do you know the answer?

**Comment by victorca25** [comment]
The self attention layers don’t need an activation, probably some leftover variable
