### ISSUE TITLE
about out of memory

### ISSUE THREAD

**Issue by shz1314** [heykeetae/Self-Attention-GAN#8]
Hi
  My GPU is 11 GB, but when i training. Always : RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58
results in the code :   result = self.forward(*input, **kwargs)

**Comment by cheonbok94** [comment]
Have you tried clone the latest version from this repository? The latest version solved memory problem.
